name: ci
on:
  push:
    branches:      
      - '**'
  pull_request:
jobs:
  ci:
    uses: lunarway/lw-shuttle-go-lib-plan/.github/workflows/plan-ci.yml@stable
    secrets: inherit
    with:
      lifecycle: stable
