name: ci
on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:
jobs:
  ci:
    uses: lunarway/lw-shuttle-go-lib-plan/.github/workflows/plan-ci.yml@stable
    secrets: inherit
    with:
      lifecycle: stable
